-- vim.opt.termguicolors = true
--
-- require("bufferline").setup({
--   options = {
--     buffer_close_icon = "",
--     close_command = "Bdelete %d",
--     close_icon = "",
--     indicator = {
--       style = "icon",
--       icon = " ",
--     },
--     left_trunc_marker = "",
--     modified_icon = "●",
--     offsets = { { filetype = "NvimTree", text = "EXPLORER", text_align = "center" } },
--     right_mouse_command = "Bdelete! %d",
--     right_trunc_marker = "",
--     show_close_icon = false,
--     show_tab_indicators = true,
--     custom_filter = function(buf_number)
--       -- since I use tabpages as per project (usually), I filter the buffers that don't belong to the current tabpage
--       -- in combination with a root/project/cwd-plugin that autosets my cwd on selection of telescope:project,
--       -- which I do on creation of a new tabpage, this works fine for me
--       if not not vim.api.nvim_buf_get_name(buf_number):find(vim.fn.getcwd(), 0, true) then
--         return true
--       end
--     end,
--     -- custom_filter = function(buf)
--       -- local tab_num = 0
--       -- for _ in pairs(vim.api.nvim_list_tabpages()) do tab_num = tab_num + 1 end
--       -- if tab_num > 1 then
--       --   return false
--       -- else
--       --   return true
--       -- end
--     -- end,
--   },
--   highlights = {
--     fill = {
--       fg = { attribute = "fg", highlight = "Normal" },
--       bg = { attribute = "bg", highlight = "StatusLineNC" },
--     },
--     background = {
--       fg = { attribute = "fg", highlight = "Normal" },
--       bg = { attribute = "bg", highlight = "StatusLine" },
--     },
--     buffer_visible = {
--       fg = { attribute = "fg", highlight = "Normal" },
--       bg = { attribute = "bg", highlight = "Normal" },
--     },
--     buffer_selected = {
--       fg = { attribute = "fg", highlight = "Normal" },
--       bg = { attribute = "bg", highlight = "Normal" },
--     },
--     separator = {
--       fg = { attribute = "bg", highlight = "Normal" },
--       bg = { attribute = "bg", highlight = "StatusLine" },
--     },
--     separator_selected = {
--       fg = { attribute = "fg", highlight = "Special" },
--       bg = { attribute = "bg", highlight = "Normal" },
--     },
--     separator_visible = {
--       fg = { attribute = "fg", highlight = "Normal" },
--       bg = { attribute = "bg", highlight = "StatusLineNC" },
--     },
--     close_button = {
--       fg = { attribute = "fg", highlight = "Normal" },
--       bg = { attribute = "bg", highlight = "StatusLine" },
--     },
--     close_button_selected = {
--       fg = { attribute = "fg", highlight = "Normal" },
--       bg = { attribute = "bg", highlight = "Normal" },
--     },
--     close_button_visible = {
--       fg = { attribute = "fg", highlight = "Normal" },
--       bg = { attribute = "bg", highlight = "Normal" },
--     },
--   },
--
-- })
